name: Trigger Repo 2 Action

on:
  workflow_dispatch

jobs:
  trigger_repo_2_action:
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event to Repo B
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: owner/repo_2
          event-type: trigger-workflow
