name: Trigger Deployment on Another Repo

on:
  push:
    branches:
      - dev

jobs:
  trigger_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: EugeneSaju/webapp_gym.git
          event-type: run